import 'package:flutter/material.dart';

class IconMapper {
  IconMapper._();

  static IconData fromString(String? icon) {
    return _map[icon] ?? Icons.category_outlined;
  }

  static const Map<String, IconData> _map = {
    // Üst kategoriler (gider)
    'shopping_cart': Icons.shopping_cart_outlined,
    'directions_car': Icons.directions_car_outlined,
    'restaurant': Icons.restaurant_outlined,
    'receipt_long': Icons.receipt_long_outlined,
    'home': Icons.home_outlined,
    'local_hospital': Icons.local_hospital_outlined,
    'movie': Icons.movie_outlined,
    'shopping_bag': Icons.shopping_bag_outlined,
    'school': Icons.school_outlined,
    'computer': Icons.computer_outlined,
    'fitness_center': Icons.fitness_center_outlined,
    'spa': Icons.spa_outlined,
    'security': Icons.security_outlined,
    'card_giftcard': Icons.card_giftcard_outlined,
    'child_care': Icons.child_care_outlined,
    'category': Icons.category_outlined,
    'subscriptions': Icons.subscriptions_outlined,
    'money_off': Icons.money_off_outlined,
    'savings': Icons.savings_outlined,
    // Alt kategoriler
    'store': Icons.store_outlined,
    'local_gas_station': Icons.local_gas_station_outlined,
    'directions_bus': Icons.directions_bus_outlined,
    'local_taxi': Icons.local_taxi_outlined,
    'local_parking': Icons.local_parking_outlined,
    'build': Icons.build_outlined,
    'local_cafe': Icons.local_cafe_outlined,
    'fastfood': Icons.fastfood_outlined,
    'delivery_dining': Icons.delivery_dining_outlined,
    'bolt': Icons.bolt_outlined,
    'water_drop': Icons.water_drop_outlined,
    'local_fire_department': Icons.local_fire_department_outlined,
    'wifi': Icons.wifi,
    'phone': Icons.phone_outlined,
    'apartment': Icons.apartment_outlined,
    'handyman': Icons.handyman_outlined,
    'medication': Icons.medication_outlined,
    'medical_services': Icons.medical_services_outlined,
    'visibility': Icons.visibility_outlined,
    'local_movies': Icons.local_movies_outlined,
    'music_note': Icons.music_note_outlined,
    'sports_esports': Icons.sports_esports_outlined,
    'palette': Icons.palette_outlined,
    'beach_access': Icons.beach_access_outlined,
    'checkroom': Icons.checkroom_outlined,
    'watch': Icons.watch_outlined,
    'face': Icons.face_outlined,
    'class': Icons.class_outlined,
    'menu_book': Icons.menu_book_outlined,
    'laptop': Icons.laptop_outlined,
    'devices': Icons.devices_outlined,
    'code': Icons.code_outlined,
    'apps': Icons.apps_outlined,
    'sports': Icons.sports_outlined,
    'science': Icons.science_outlined,
    'content_cut': Icons.content_cut_outlined,
    'face_retouching_natural': Icons.face_retouching_natural_outlined,
    'air': Icons.air,
    'health_and_safety': Icons.health_and_safety_outlined,
    'car_crash': Icons.car_crash_outlined,
    'home_repair_service': Icons.home_repair_service_outlined,
    'fact_check': Icons.fact_check_outlined,
    'shield': Icons.shield_outlined,
    'volunteer_activism': Icons.volunteer_activism_outlined,
    'mosque': Icons.mosque_outlined,
    'child_friendly': Icons.child_friendly_outlined,
    'toys': Icons.toys_outlined,
    'theater_comedy': Icons.theater_comedy_outlined,
    'directions_car_filled': Icons.directions_car_filled,

    // Gelir
    'payments': Icons.payments_outlined,
    'work': Icons.work_outlined,
    'trending_up': Icons.trending_up,
    'account_balance': Icons.account_balance_outlined,
    'attach_money': Icons.attach_money,
    'paid': Icons.paid_outlined,
    'stars': Icons.stars_outlined,
    'assignment': Icons.assignment_outlined,
    'support_agent': Icons.support_agent_outlined,
    'percent': Icons.percent,
    'diamond': Icons.diamond_outlined,
    'price_check': Icons.price_check_outlined,
    'star': Icons.star_outline,
    'sell': Icons.sell_outlined,
    'laptop_mac': Icons.laptop_mac_outlined,

    // Hesap türleri
    'account_balance_wallet': Icons.account_balance_wallet_outlined,
    'credit_card': Icons.credit_card_outlined,
    'currency_lira': Icons.currency_lira,

    // Navigasyon
    'dashboard': Icons.dashboard_outlined,
    'pie_chart': Icons.pie_chart_outline,
    'handshake': Icons.handshake_outlined,
    'settings': Icons.settings_outlined,
    'person': Icons.person_outlined,
    'notifications': Icons.notifications_outlined,
    'help': Icons.help_outlined,
    'logout': Icons.logout,

    // İşlem kaynakları
    'edit': Icons.edit_outlined,
    'repeat': Icons.repeat,
    'account_balance_outlined': Icons.account_balance_outlined,

    // Genel
    'add': Icons.add,
    'close': Icons.close,
    'check': Icons.check,
    'arrow_forward': Icons.arrow_forward_ios,
    'visibility_off': Icons.visibility_off_outlined,
    'camera_alt': Icons.camera_alt_outlined,
    'image': Icons.image_outlined,
    'flash_on': Icons.flash_on,
    'flash_off': Icons.flash_off,
  };
}
